const PATHS = {
  HOME: '/',
  SIGNIN: '/sign-in',
  SIGNUP: '/sign-up',
  FORGET_PASSWORD: '/forget-password',
  RESET_PASSWORD: '/reset-password',
  ACCOUNT_SETTINGS: '/account-settings',
  ORDER_HISTORY: '/order-history',
  LOGIN_SECURITY: '/login-and-security',
  ADDRESS: '/address',
  WISHLIST: '/wishlist',
  COMPLETE_PROFILE: '/complete-profile',
  PRODUCT_DETAILS: '/product/:id',
  SEARCH_RESULT: '/search',
  ADD_TO_CART: '/add-to-cart',
  CART: '/cart',
  CATEGORY_BANNER: '/category/:id',
  WOW_BANNER: '/wow/:slug',
  CUSTOMER_CARE: '/customer-care',
  ABOUT_US: '/about-us',
  CATEGORIES: '/categories',
  NOT_FOUND: '*',
};

export default PATHS;
